export const LOAD_RECENT_JOBS = 'LOAD_RECENT_JOBS_PENDING';
//export const LOAD_RECENT_JOBS_SUCCESS = 'LOAD_RECENT_JOBS_FULFILLED';
//export const LOAD_RECENT_JOBS_ERROR = 'LOAD_RECENT_JOBS_REJECTED';

export const LOAD_POPULAR_JOBS = 'LOAD_POPULAR_JOBS';
//export const LOAD_POPULAR_JOBS_SUCCESS = 'LOAD_POPULAR_JOBS_FULFILLED';
//export const LOAD_POPULAR_JOBS_ERROR = 'LOAD_POPULAR_JOBS_REJECTED';