export const INITIAL_STATE = {
    recentJobs: [],
    errorRecentJobs: false,
    loadingRecentJobs: false,
    popularJobs: [],
    errorPopularJobs: false,
    loadingPopularJobs: false,
    searchJob: [],
    errorSearchJobs: false,
    loadingSearchJobs: false,
    job: {},
    errorJob: false,
    loadingJob: false,
    applications: [],
    errorApplications: false,
    loadingApplications: false,
    favorites: [],
    errorFavorites: false,
    loadingFavorites: false,
}